### ISSUE TITLE
Cart functionality

### ISSUE THREAD

**Issue by aambrose1** [Newt-Tea/Intro_SE_WebApp_Group1#72]
Add the features needed to have the shopping cart working and saving orders to order table

**Comment by Newt-Tea** [comment]
in commit 13bd7ca58ac4bec34a9d5639e0968c095622afc2 on #80 I began an add_to_cart function that needs to be completed for the product detail page to work properly

**Comment by Newt-Tea** [comment]
There is an issue with the order model. It needs to have another user specific ID that can be displayed on order_history. Currently every user shares the app_order table in the db so each order is going to the same table, meaning a user's first order will show up as whatever number order the website is on.
